drinks/urls.py
from django.urls import path


from drinks.views import (
    DrinkListView,
    DrinkCreateView,
)

urlpatterns = [
    path("", DrinkListView.as_view(), name="drinks_list"),
    path("createdrink/", DrinkCreateView.as_view(), name="create_drink"),
]

mixology/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("drinks/", include("drinks.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("drinks_list")), name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

drinks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class Drink(models.Model):
    name = models.CharField(max_length=100, unique=True, blank=False)
    image = models.URLField(blank=False)
    instructions = models.TextField(null=True, blank=True)
    creator = models.ForeignKey(
        USER_MODEL, related_name="drinks", on_delete=models.CASCADE, null=True
    )
    created = models.DateTimeField(auto_now_add=True)
    glass = models.ForeignKey(
        "Glass", related_name="drink", on_delete=models.PROTECT, null=True, blank=True
    )

    EASY = "1"
    MODERATE = "2"
    ADVANCED = "3"

    difficulty_choices = [
        (EASY, "easy"),
        (MODERATE, "moderate"),
        (ADVANCED, "advanced"),
    ]

    difficulty = models.CharField(max_length=2, choices=difficulty_choices, blank=False)

    WHISKEY = "W"
    VODKA = "V"
    TEQUILA = "T"
    RUM = "R"
    GIN = "G"
    BRANDY = "B"
    OTHER = "O"

    liquor_choices = [
        (WHISKEY, "Whiskey"),
        (VODKA, "Vodka"),
        (TEQUILA, "Tequila"),
        (RUM, "Rum"),
        (GIN, "Gin"),
        (BRANDY, "Brandy"),
        (OTHER, "Other"),
    ]

    liquor_type = models.CharField(max_length=2, choices=liquor_choices, blank=False)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.CharField(max_length=200, blank=True)
    name = models.CharField(max_length=300)
    drink = models.ForeignKey(Drink, related_name="drinks", on_delete=models.CASCADE)

    def __str__(self):
        if self.amount:
            return f"{self.amount} of {self.name}"
        else:
            return self.name


class Glass(models.Model):
    class Meta:
        verbose_name_plural = "glasses"

    type = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.type


class Garnish(models.Model):
    class Meta:
        verbose_name_plural = "garnish"

    name = models.CharField(max_length=200)
    drink = models.ForeignKey(
        "Drink", related_name="garnish", on_delete=models.PROTECT, null=True, blank=True
    )

    def __str__(self):
        return self.name

drinks/forms.py
from django import forms
from betterforms.multiform import MultiModelForm

from .models import Drink, Ingredient, Garnish, Glass

accounts/views.py
from django.shortcuts import render

# Create your views here.

drinks/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from extra_views import (
    CreateWithInlinesView,
    UpdateWithInlinesView,
    InlineFormSetFactory,
)

from .models import Drink, Ingredient, Garnish

# Create your views here.


class DrinkListView(ListView):
    model = Drink
    template_name = "drinks/list.html"
    paginate_by = 4


# class DrinkCreateView(LoginRequiredMixin, CreateView):
#     model = Drink
#     template_name = "drinks/new.html"
#     fields = [
#         "name",
#         "image",
#         "difficulty",
#         "liquor_type",
#         "glass",
#     ]

#     def form_valid(self, form):
#         new_receipe = form.save(commit=False)
#         new_receipe.creator = self.request.user
#         new_receipe.save()
#         return redirect("create_ingredient", pk=new_receipe.id)


class IngredientInline(InlineFormSetFactory):
    model = Ingredient
    fields = ["amount", "name"]


class GarnishInline(InlineFormSetFactory):
    model = Garnish
    fields = ["name"]


class DrinkCreateView(LoginRequiredMixin, CreateWithInlinesView):
    model = Drink
    inlines = [IngredientInline, GarnishInline]
    fields = ["name", "image", "instructions", "glass", "difficulty", "liquor_type"]
    template_name = "drinks/ingredients.html"

    def get_object(self, queryset=None):
        try:
            return super().get_object(queryset)
        except AttributeError:
            return None

    def get_success_url(self) -> str:
        return reverse_lazy("drinks_list")

drinks/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %} {% endblock title %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Palatino", sans-serif}
    </style>
</head>
<body>
    <header>
        {% block pagination %}
        {% endblock pagination %}
    </header>
    <main>
    {% block content %}
    {% endblock content %}
    </main>
    <footer>
    </footer>
</body>
</html>

drinks/templates/drinks/ingredients.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
{% csrf_token %}
    {{ form.as_ul }}

    {% for formset in inlines %}
      {{ formset.as_ul }}
    {% endfor %}

    <input type="submit" value="Submit" />
  </form>

{% endblock content %}

drinks/templates/drinks/list.html
{% extends 'base.html' %}

{% block title %} <title>Drinks</title> {% endblock title %}

{% block pagination %}
    <div class="pagination1">
        <div>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>

            {% for page_number in page_obj.paginator.page_range %}
                <a href="?page={{page_number}}"class="{% if page_number == page_obj.number %}active{% endif %}">
                {{page_number}}
            </a>
            {% endfor %}
            <a> &raquo; </a>
            {% endif %}

            {% if page_obj.has_next %}
            <a> &laquo; </a>

            {% for page_number in page_obj.paginator.page_range %}
                <a href="?page={{page_number}}"class="{% if page_number == page_obj.number %}active{% endif %}">
                {{page_number}}
            </a>
            {% endfor %}
            <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            {% endif %}
        </div>
    </div>
{% endblock pagination %}

{% block content %}
        <h1 class="page-title">Drink Up</h1>
        <div class="recipe-grid">
            {% for drink in drink_list %}
                <div class="{% cycle 'grid-item1' 'grid-item2' %}">
                    <div> <img class="grid-image" src="{{ drink.image }}"> </div>
                    <div class="drink-name">{{drink.name}}</div>
                    <table style="width:100%" class="header">
                        <tr>
                            <th class="ingredients">Ingredients</th>
                            <th class="difficulty">Difficulty
                                {% if drink.difficulty == "1" %}
                                <img src="https://chopinvodka.com/wp-content/uploads/2019/07/difficulty_easy.png">
                                {% elif drink.difficulty == "2" %}
                                <img src="https://chopinvodka.com/wp-content/uploads/2019/07/difficulty_medium.png">
                                {% elif drink.difficulty == "3" %}
                                <img src="https://chopinvodka.com/wp-content/uploads/2019/07/difficulty_hard.png">
                                {% endif %}
                            </th>
                        </tr>
                    </table>
                    <table>
                        {% for ingredient in drink.drinks.all %}
                            <tr>
                                <td class="drink-ingredients">{{ingredient.amount}} {{ingredient.name}}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endfor %}
        </div>
{% endblock content %}


{% comment %}  {% endcomment %}

drinks/templates/drinks/new.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button>Submit</button>

{% endblock content %}

drinks/templates/drinks/practice.html
<!DOCTYPE html>
<html>
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
</head>
<body>

<!-- Sidebar (hidden by default) -->
<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()"
  class="w3-bar-item w3-button">Close Menu</a>
  <a href="#food" onclick="w3_close()" class="w3-bar-item w3-button">Food</a>
  <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">About</a>
</nav>

<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">☰</div>
    <div class="w3-right w3-padding-16">Mail</div>
    <div class="w3-center w3-padding-16">My Food</div>
  </div>
</div>

<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">

  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="food">
    <div class="w3-quarter">
      <img src="/w3images/sandwich.jpg" alt="Sandwich" style="width:100%">
      <h3>The Perfect Sandwich, A Real NYC Classic</h3>
      <p>Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/steak.jpg" alt="Steak" style="width:100%">
      <h3>Let Me Tell You About This Steak</h3>
      <p>Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/cherries.jpg" alt="Cherries" style="width:100%">
      <h3>Cherries, interrupted</h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
      <p>What else?</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/wine.jpg" alt="Pasta and Wine" style="width:100%">
      <h3>Once Again, Robust Wine and Vegetable Pasta</h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
  </div>

  <!-- Second Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center">
    <div class="w3-quarter">
      <img src="/w3images/popsicle.jpg" alt="Popsicle" style="width:100%">
      <h3>All I Need Is a Popsicle</h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/salmon.jpg" alt="Salmon" style="width:100%">
      <h3>Salmon For Your Skin</h3>
      <p>Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/sandwich.jpg" alt="Sandwich" style="width:100%">
      <h3>The Perfect Sandwich, A Real Classic</h3>
      <p>Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/croissant.jpg" alt="Croissant" style="width:100%">
      <h3>Le French</h3>
      <p>Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
  </div>

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
      <a href="#" class="w3-bar-item w3-black w3-button">1</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>

  <hr id="about">

  <!-- About Section -->
  <div class="w3-container w3-padding-32 w3-center">
    <h3>About Me, The Food Man</h3><br>
    <img src="/w3images/chef.jpg" alt="Me" class="w3-image" style="display:block;margin:auto" width="800" height="533">
    <div class="w3-padding-32">
      <h4><b>I am Who I Am!</b></h4>
      <h6><i>With Passion For Real, Good Food</i></h6>
      <p>Just me, myself and I, exploring the universe of unknownment. I have a heart of love and an interest of lorem ipsum and mauris neque quam blog. I want to share my world with you. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
    </div>
  </div>
  <hr>

  <!-- Footer -->
  <footer class="w3-row-padding w3-padding-32">
    <div class="w3-third">
      <h3>FOOTER</h3>
      <p>Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
      <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </div>

    <div class="w3-third">
      <h3>BLOG POSTS</h3>
      <ul class="w3-ul w3-hoverable">
        <li class="w3-padding-16">
          <img src="/w3images/workshop.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Lorem</span><br>
          <span>Sed mattis nunc</span>
        </li>
        <li class="w3-padding-16">
          <img src="/w3images/gondol.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Ipsum</span><br>
          <span>Praes tinci sed</span>
        </li>
      </ul>
    </div>

    <div class="w3-third w3-serif">
      <h3>POPULAR TAGS</h3>
      <p>
        <span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">New York</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dinner</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Salmon</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">France</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Drinks</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Flavors</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Cuisine</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Chicken</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dressing</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fried</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fish</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Duck</span>
      </p>
    </div>
  </footer>

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}
</script>

</body>
</html>

drinks/templates/drinks/test.html
{% extends 'base.html' %}


{% block content %}

<h1>
{% for drink in drink_list %}
    <ul>
        <li>{{drink.name}}</li>
        <li>{% if drink.difficulty == "1" %}
        show1
        {% endif %}
        </li>
    </ul>
{% endfor %}
</h1>

{% endblock content %}